# Generated by Django 5.2.10 on 2026-01-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Icon')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Page Title')),
                ('logo', models.CharField(blank=True, max_length=15, verbose_name="Logo uchun so'z")),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Home page uchun rasm')),
                ('job', models.CharField(max_length=50, verbose_name='Kasb')),
                ('language', models.CharField(max_length=50, verbose_name='Dasturlash tillari')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ism va familiya')),
                ('description', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
