# Generated by Django 5.2.10 on 2026-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name="About uchun so'z")),
                ('description', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=50, verbose_name='Emoji')),
                ('skill', models.CharField(blank=True, max_length=50, verbose_name='Skill')),
                ('description', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
