# Generated by Django 5.2.10 on 2026-01-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_aboutpage_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='aboout',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sayt.aboutpage'),
            preserve_default=False,
        ),
    ]
