# Generated by Django 5.2.10 on 2026-01-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_skill_aboout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Blog kategoriyasi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Blog nomi ')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
