# Generated by Django 5.2.10 on 2026-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0005_blog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, verbose_name="Blog haqida umumiy ma'lumot"),
        ),
        migrations.AddField(
            model_name='blog',
            name='detail_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Detail sahifa uchun nom'),
        ),
    ]
