# Generated by Django 5.2.10 on 2026-01-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0006_blog_body_blog_detail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created',
            new_name='created_at',
        ),
    ]
