# Generated by Django 5.2.10 on 2026-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0007_rename_created_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kontakt uchun Adress'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Kontakt uchun Email'),
        ),
    ]
