# Generated by Django 5.2.10 on 2026-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayt.homepage')),
            ],
        ),
    ]
