# Generated by Django 5.2.10 on 2026-02-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0011_homelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
